### ISSUE TITLE
ブログタイトルが白い

### ISSUE THREAD

**Issue by momeemt** [Comamoca/blog#1]
![image](https://github.com/Comamoca/blog/assets/43488453/944777a6-c042-4638-965a-7913b442ba22)

実装中かとは思うのですが一応報告しておきます :pray:

## 環境
- Chrome バージョン: 117.0.5938.92（Official Build） （arm64）
- macOS Ventura 13.0
- 外観モード: ダーク

**Comment by Comamoca** [comment]
issueを一年以上放置していてすみません...
問題を修正するcommitをしたので確認してみてください。

**Comment by momeemt** [comment]
確認しました！ご対応いただきありがとうございました🐬
